### PR TITLE
resolve error because data doesn't exist + start typescript definition

### PR DESCRIPTION
**Pull request by thib3113**

### CODE REVIEW

**Comment by willow9886** [comment]
Thanks, merging. We need more work on Typescript configuration (i.e. build + config + convert javascript)...

**Comment by thib3113** [comment]
Hum, not totally sure of what you are saying (i'm not really good in english) .

But, if you need to convert it to typescript, take a look at that : https://github.com/thib3113/SCIM-Node/tree/typescript

I've converted some parts of SCIM-Node to typescript, for personnal use .

In fact, I've converted the SCIM2 to typescript . ( but because I don't understand how secure way work for the moment, I've also add a way to use the SCIM test mode ) . 

If you want, we can merge this work in a new branch here, and start working in .

**Comment by willow9886** [comment]
cc @ldeveloperl1985

**Comment by ldeveloperl1985** [comment]
Hi @thib3113 ,

I see your work in your repository with typescript configuration and build, that is what we want for the fully complete library.

We would like to merge your whole code in new_branch here. I have created `update_typescript` branch. Please make PR with this branch. I'll review your PR.

Thank you

**Comment by thib3113** [comment]
Hi, 
I've done a PR . 
Just remember, it's just the beginning . I've done some tests with my use ( on a test gluu server ) .

**Pull request merged**
